universe = docker
docker_image = astral/uv:debian
executable = run_pfn_training.sh
arguments = $(script) $(fold) $(n_bins) $(mol_feat) $(unmasked_weight) $(physcem) $(norm) $(dropout) $(lr) $(obj) $(act)
output = logs/pfn_train.$(ClusterId).$(ProcId).out
error = logs/pfn_train.$(ClusterId).$(ProcId).err
log = logs/pfn_train.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_memory = 400GB
requirements = (GPUs_Capability >= 7.0) && (GPUs_GlobalMemoryMb >= 16000)
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue fold, script, n_bins, mol_feat, unmasked_weight, physcem, norm, dropout, lr, obj, act from (
  0, scripts/pfn_train.py, 1000, allfp, 0, 0.25, minmax, 0.0, 2.5e-5, crps, GELU
  0, scripts/pfn_train.py, 1000, allfp, 0, 0.25, minmax, 0.0, 7.5e-5, crps, GELU
  0, scripts/pfn_train.py, 1000, allfp, 0.0001, 0.25, minmax, 0.0, 5e-5, crps, GELU
  0, scripts/pfn_train.py, 1000, allfp, 0.001, 0.25, minmax, 0.0, 5e-5, crps, GELU
  0, scripts/pfn_train.py, 1000, allfp, 0, 0.10, minmax, 0.0, 5e-5, crps, GELU
  0, scripts/pfn_train.py, 1000, allfp, 0, 0.40, minmax, 0.0, 5e-5, crps, GELU
)
