universe = docker
docker_image = astral/uv:debian
executable = run_training.sh
arguments = $(script) $(seed) $(dataset) $(method) $(fold) $(mol_feat)
output = logs/train_dti.$(ClusterId).$(ProcId).out
error = logs/train_dti.$(ClusterId).$(ProcId).err
log = logs/train_dti.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 16
request_memory = 64G
requirements = (GPUs_Capability >= 7.0) && (GPUs_GlobalMemoryMb >= 16000)
+WantGPUHomeMounted = true
queue fold, script, seed, dataset, method, mol_feat from (
    0, scripts/train.py, 1, landrum, sets, morgan
    1, scripts/train.py, 1, landrum, sets, morgan
    2, scripts/train.py, 1, landrum, sets, morgan
    3, scripts/train.py, 1, landrum, sets, morgan
    4, scripts/train.py, 1, landrum, sets, morgan
    0, scripts/train.py, 1, omnivore, sets, morgan
    1, scripts/train.py, 1, omnivore, sets, morgan
    2, scripts/train.py, 1, omnivore, sets, morgan
    3, scripts/train.py, 1, omnivore, sets, morgan
    4, scripts/train.py, 1, omnivore, sets, morgan
    0, scripts/train.py, 1, kinodata, sets, morgan
    1, scripts/train.py, 1, kinodata, sets, morgan
    2, scripts/train.py, 1, kinodata, sets, morgan
    3, scripts/train.py, 1, kinodata, sets, morgan
    4, scripts/train.py, 1, kinodata, sets, morgan
)
