universe = docker
docker_image = gjoschka/kinodata3d-b0:2.3.0-cuda12.1
executable = train_dti.sh
output = train_dti.$(ClusterId).out
error = train_dti.$(ClusterId).err
log = train_dti.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 16
request_memory = 64G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue
