universe = docker
docker_image = astral/uv:debian
executable = run_training.sh
arguments = $(script) $(seed) $(dataset) $(fold)
output = logs/train_dti.$(ClusterId).$(ProcId).out
error = logs/train_dti.$(ClusterId).$(ProcId).err
log = logs/train_dti.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_memory = 64G
requirements = (GPUs_Capability >= 7.0) && (GPUs_GlobalMemoryMb >= 17000)
+WantGPUHomeMounted = true
queue fold, script, seed, dataset from (
   0, scripts/train.py, 0, landrum
   1, scripts/train.py, 0, landrum
   2, scripts/train.py, 0, landrum
   3, scripts/train.py, 0, landrum
   4, scripts/train.py, 0, landrum
   0, scripts/train.py, 0, kinodata
   1, scripts/train.py, 0, kinodata
   2, scripts/train.py, 0, kinodata
   3, scripts/train.py, 0, kinodata
   4, scripts/train.py, 0, kinodata
   0, scripts/train.py, 0, omnivore
   1, scripts/train.py, 0, omnivore
   2, scripts/train.py, 0, omnivore
   3, scripts/train.py, 0, omnivore
   4, scripts/train.py, 0, omnivore
)

