universe = docker
docker_image = astral/uv:debian
executable = run_training.sh
arguments = $(script) $(seed) $(dataset) $(method) $(fold) $(mol_feat)
output = logs/train_dti.$(ClusterId).$(ProcId).out
error = logs/train_dti.$(ClusterId).$(ProcId).err
log = logs/train_dti.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 8
request_memory = 64G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue fold, script, seed, dataset, method, mol_feat from (
    0, scripts/train.py, 0, landrum, pfn, morgan
    1, scripts/train.py, 0, landrum, pfn, morgan
    2, scripts/train.py, 0, landrum, pfn, morgan
    3, scripts/train.py, 0, landrum, pfn, morgan
    4, scripts/train.py, 0, landrum, pfn, morgan
    0, scripts/train.py, 0, chembl, pfn, morgan
    1, scripts/train.py, 0, chembl, pfn, morgan
    2, scripts/train.py, 0, chembl, pfn, morgan
    3, scripts/train.py, 0, chembl, pfn, morgan
    4, scripts/train.py, 0, chembl, pfn, morgan
)
