universe = docker
docker_image = gjoschka/kinodata3d-b0:2.3.0-cuda12.1
executable = run_training.sh
arguments = $(script) $(seed) $(dataset) $(method)
output = logs/train_dti.$(ClusterId).$(ProcId).out
error = logs/train_dti.$(ClusterId).$(ProcId).err
log = logs/train_dti.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 16
request_memory = 64G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue script, seed, dataset, method from (
    scripts/train.py, 0, atcc, ic50
    scripts/train.py, 0,atcc, pair
    scripts/train.py, 0, kinodata, ic50
    scripts/train.py, 0, kinodata, pair
    scripts/train.py, 0, landrum, ic50
    scripts/train.py, 0, landrum, pair
    scripts/train.py, 0, landrum_large, ic50
    scripts/train.py, 0, landrum_large, pair
)
